# Generated by Django 2.2.3 on 2019-07-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0006_perfil_bloqueados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=300)),
                ('amei', models.IntegerField()),
                ('odiei', models.IntegerField()),
                ('triste', models.IntegerField()),
                ('legal', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_posts', to='perfis.Perfil')),
            ],
        ),
    ]
