# Generated by Django 2.2.3 on 2019-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='marcacoes',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
