# Generated by Django 2.2.3 on 2019-07-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0009_perfil_is_active'),
        ('post', '0007_auto_20190716_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='marcacoes',
        ),
        migrations.CreateModel(
            name='Marcacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
