# Generated by Django 2.2.3 on 2019-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20190716_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacoes',
            name='marcado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marcacoes',
            name='post',
            field=models.IntegerField(),
        ),
    ]
