# Generated by Django 2.2.1 on 2019-07-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_auto_20190710_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(related_name='pessoa_fisica', to='perfis.Perfil'),
        ),
    ]
