# Generated by Django 2.2.1 on 2019-07-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_auto_20190711_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(to='perfis.Perfil'),
        ),
    ]
