# Generated by Django 2.2.1 on 2019-07-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20190711_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(related_name='amigos', to='perfis.Perfil'),
        ),
    ]
