# Generated by Django 2.2.1 on 2019-07-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_auto_20190712_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloqueados',
            field=models.ManyToManyField(to='perfis.Perfil'),
        ),
    ]
