# Generated by Django 2.2.3 on 2019-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_perfil_bloqueados'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.FileField(null=True, upload_to='media/perfis/'),
        ),
    ]
